# .goreleaser.yml
builds:
  - main: ./cmd/lazyjack.go
    binary: lazyjack
    goos:
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  files:
    - LICENSE
    - sample-config.yaml
sign:
  artifacts: checksum
