# deprecated
# plugin: bridge
general:
    plugin: bridge  # default value
topology:
    <master-name>:
        interface: "<intf-name>"
        opmodes: "master dns64 nat64"
        id: 2
    <minion-1-name>:
        interface: "<intf-name>"
        opmodes: "minion"
        id: 3
    <minion-2-name>:
        interface: "<intf-name>"
        opmodes: "minion"
        id: 4
support_net:
    cidr: "fd00:10::/64"
    v4cidr: "172.18.0.0/16"
mgmt_net:
    cidr: "fd00:20::/64"
pod_net:
    cidr: "fd00:40::/72"
service_net:
    cidr: "fd00:30::/110"
nat64:
    v4_cidr: "172.18.0.128/25"
    v4_ip: "172.18.0.200"
    ip: "fd00:10::200"
dns64:
    remote_server: "64.102.6.247"
    cidr: "fd00:10:64:ff9b::/96"
    ip: "fd00:10::100"
