# Dual-stack sample config
general:
    mode: dual-stack
    plugin: bridge  # default value (can be ptp)
topology:
    <master-name>:
        interface: "<intf-name>"
        opmodes: "master"
        id: 2
    <minion-1-name>:
        interface: "<intf-name>"
        opmodes: "minion"
        id: 3
    <minion-2-name>:
        interface: "<intf-name>"
        opmodes: "minion"
        id: 4
mgmt_net:
    cidr: "10.192.0.0/24"
    cidr2: "fd00:20::/64"
pod_net:
    cidr: "10.244.0.0/16"
    cidr2: "fd00:40::/72"
service_net:
    cidr: "10.96.0.0/12"  # when support for IPv6 service network can use "fd00:30::/110"
